Updating translations
Koi-foo/kernel-manager pull request #9
Opened 2021-11-15 12:09 UTC by gostsdmitry

Hindi, Simplified Chinese, Traditional Chinese.

2021-11-15 19:26 UTC, Koi-foo commented on locale/hi/LC_MESSAGES/kernel_manager.po
>  #: form/main_win.py:308
Куда делся этот блок? :)

2021-11-15 19:27 UTC, Koi-foo commented on locale/zh/LC_MESSAGES/kernel_manager.po
>  #: form/main_win.py:308
То же самое блок исчез.

2021-11-15 19:27 UTC, Koi-foo commented on locale/zh_TW/LC_MESSAGES/kernel_manager.po
>  #: form/main_win.py:308
И тут

2021-11-15 19:30 UTC, gostsdmitry commented on locale/zh_TW/LC_MESSAGES/kernel_manager.po
>  #: form/main_win.py:308
Странно. Делал на poedit. Сейчас ещё раз гляну.

2021-11-15 19:38 UTC, Koi-foo requested changes
Блок разметки из строки form/main_win.py:308 исчезает. Это может происходить если например в Poedit обновить из кода, тогда он автоматически сотрет блоки.
В качестве альтернативы можно просто сделать изменения в файлах .../hi/LC_MESSAGES/kernel_manager.po и т.д потом сохранить их без обновления. Тогда Poedit не должен затирать блоки.

2021-11-15 19:38 UTC, gostsdmitry commented on locale/zh/LC_MESSAGES/kernel_manager.po
>  #: form/main_win.py:308
Можешь посмотреть в моём форке - там всё нормально.

2021-11-15 19:43 UTC, gostsdmitry commented on locale/hi/LC_MESSAGES/kernel_manager.po
>  #: form/main_win.py:308
У тебя же только один блок надо было обновить?

2021-11-15 19:43 UTC, Koi-foo commented on locale/zh_TW/LC_MESSAGES/kernel_manager.po
>  #: form/main_win.py:308
Вот есть параллельно посмотреть то хорошо видно 
https://github.com/Koi-foo/kernel-manager/pull/9/files?diff=split&w=0

2021-11-15 19:48 UTC, Koi-foo commented on locale/hi/LC_MESSAGES/kernel_manager.po
>  #: form/main_win.py:308
Не, скорее всего это Pоedit затер. Попробуй не нажимать кнопку обновить из кода или pot, а прост о исправить *.po и сохранить.

2021-11-15 19:52 UTC, gostsdmitry commented on locale/zh_TW/LC_MESSAGES/kernel_manager.po
>  #: form/main_win.py:308
Я думал это ты его удалил, как ненужный )))

2021-11-15 19:55 UTC, gostsdmitry commented on locale/zh_TW/LC_MESSAGES/kernel_manager.po
>  #: form/main_win.py:308
А затёр он его из-за вот этой метки: #, fuzzy

2021-11-15 20:03 UTC, Koi-foo commented on locale/zh_TW/LC_MESSAGES/kernel_manager.po
>  #: form/main_win.py:308
Там просто странная цветовая дифференциация прямо как с малиновыми штанами в Кин-дза-дза. Бледно розовый это удаленные строки, чуть ярче, но тоже розовый замененные, а совсем розовый близко к красному и ярко зеленый это замена символов.

2021-11-15 20:38 UTC, gostsdmitry commented on locale/zh_TW/LC_MESSAGES/kernel_manager.po
>  #: form/main_win.py:308
Китайский традиционный готов. Куда вставить? На место 316-й стоки? Это один блок.

2021-11-15 22:06 UTC, gostsdmitry commented on locale/zh_TW/LC_MESSAGES/kernel_manager.po
>  #: form/main_win.py:308
Отредактировал прямо здесь на сайте. На каждый язык патч с указанием языка.

2021-11-18 21:14 UTC, merged

2021-11-18 21:39 UTC, gostsdmitry commented
Этот PR ты зря одобрил.